---
apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
    name: tanka-plugin
spec:
    version: v1.0
    generate:
        command:
            - sh
            - "-c"
            - /generate

    init:
        command:
            - sh
            - "-c"
            - /init

    discover:
        find:
            command: ["sh", "-c", "/discover"]
