---
apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
    name: tanka-plugin
spec:
    version: v1.0
    generate:
        command:
            - bash
            - "-c"
            - "/generate 2>&1 | tee /tmp/generate.log.$(date +%s)"

    init:
        command:
            - bash
            - "-c"
            - "/init 2>&1 | tee /tmp/init.log.$(date +%s)"

    discover:
        find:
            command: ["bash", "-c", "/discover 2>&1 | tee /tmp/discover.log.$(date +%s)"]
